image:
  repository: githubrunnertestregistry.azurecr.io/prediction
  tag: "v2"
  pullPolicy: IfNotPresent
namespace: backend
replicaCount: 2

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false

resources:
  limits:
    cpu: "500m"
    memory: "512Mi"
  requests:
    cpu: "250m"
    memory: "256Mi"

imagePullSecrets:
  - name: docker-registry-credentials