apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-processing
  namespace: backend
  labels:
    app: data-processing
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: data-processing
  template:
    metadata:
      labels:
        app: data-processing
    spec:
      imagePullSecrets:
        {{- toYaml .Values.imagePullSecrets | nindent 8 }}
      containers:
        - name: data-processing
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8000
