apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-ingestion
spec:
  type: {{ .Values.service.type }}
  selector:
    app: ingestion
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 8000
