apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification
  namespace: backend
  labels:
    app: notification
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: notification
  template:
    metadata:
      labels:
        app: notification
    spec:
      imagePullSecrets:
        {{- toYaml .Values.imagePullSecrets | nindent 8 }}
      containers:
        - name: notification
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8000
